name: Publish

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

permissions:
  contents: read


jobs:

  build:
    if: github.repository == 'jamielinux/httpdate'
    name: 'Build'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:

      - name: 'Harden Runner'
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - name: 'Checkout'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade build

      - name: 'Build'
        run: |
          python -m build

      - name: 'Upload dist'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: dist
          path: 'dist/*'
          if-no-files-found: error
          retention-days: 30


  publish:
    if: github.repository == 'jamielinux/httpdate'
    name: 'Publish to PyPI'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - name: 'Harden Runner'
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            pypi.org:443
            pypi.python.org:443
            upload.pypi.org:443

      - name: 'Download dist'
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: dist
          path: dist

      - name: 'Publish'
        uses: pypa/gh-action-pypi-publish@29930c9cf57955dc1b98162d0d8bc3ec80d9e75c  # v1.8.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          print-hash: true
